site_name: Crimson Desert WIKI
theme:
  name: material
  custom_dir: material
  logo: img/logo.png
  favicon: img/black_logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Night
    # Palette toggle for dark mode
    - scheme: slate
      primary: brown
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Light
  features:
    - announce.dismiss
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    #- content.tabs.link
    - content.tooltips
    - header.autohide
    #- navigation.expand
    - navigation.footer
    - navigation.indexes
    #- navigation.instant
    #- navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

site_url: https://github.com/crimson-desert
repo_url: https://github.com/vlad15277
repo_name: CDW
edit_uri: edit/main/docs/


extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/tablesort.js

hooks:
  - hooks/page_links_by_tag.py
# - hooks/all_pages_table.py

plugins:
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
  - search: {}
  - autolinks: {}
  # - git-revision-date-localized: {}

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      user: V_A_R_A_G
      provider: github
      repo: website
      repo_url_shorthand: true
      repo_url_shortener: false
      social_url_shorthand: false
      social_url_shortener: false
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  consent:
    actions:
      - accept
      - manage
  generator: false